upstream employee_ms {
    server employee-ms:8000;
}

upstream payroll_ms {
    server payroll-ms:8000;
}

upstream leave_ms {
    server leave-ms:8000;
}

server {
    listen 80;

    location /employees {
        proxy_pass http://employee_ms;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Correlation-ID $request_id;
    }

    location /departments {
        proxy_pass http://employee_ms;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Correlation-ID $request_id;
    }

    location /employee-roles {
        proxy_pass http://employee_ms;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Correlation-ID $request_id;
    }

    location /payroll {
        proxy_pass http://payroll_ms;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Correlation-ID $request_id;
    }

    location /leave {
        proxy_pass http://leave_ms;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Correlation-ID $request_id;
    }

    location /health {
        proxy_pass http://employee_ms;
        proxy_set_header Host $host;
    }
}
